apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-mongo
spec:
  selector:
    app: chatapp-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-mongo
spec:
  selector:
    matchLabels:
      app: chatapp-mongo
  template:
    metadata:
      labels:
        app: chatapp-mongo
    spec:
      containers:
        - name: chatapp-mongo
          image: mongo:6.0.2-focal
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: chatapp-mongo-pvc
