apiVersion: v1
kind: Service
metadata:
  name: chatapp-backend
spec:
  selector:
    app: chatapp-backend
  ports:
    - port: 4200
      targetPort: 4200
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp-backend
  template:
    metadata:
      labels:
        app: chatapp-backend
    spec:
      containers:
        - name: chatapp-backend
          image: sentienta/chatapp-backend:0.0.1
          ports:
            - containerPort: 4200
          env:
            - name: MONGO_URL
              value: mongodb://chatapp-mongo:27017/dev
          imagePullPolicy: Always
